### ISSUE TITLE
Is the generation of parameters inside the swagger correct?

### ISSUE THREAD

**Issue by loucass003** [samchon/nestia#756]
## Question

When using TypedQuery() nestia generates the following yaml inside the swagger but is this really correct?

Using this Query as an example
```ts
export interface QueryShow {
  showId: string;
  otherId: string
}

public async show(@TypedQuery() query: QueryShow) {}
```

This is what nestia currently generates
```yaml
 parameters:
        - name: query
          in: query
          schema:
            $ref: '#/components/schemas/QueryShow'
          description: ''
          required: true
```

Souldnt it be this instead?
```yaml
 parameters:
        - name: showId
          in: query
          schema:
            type: string
          description: ''
          required: true
        - name: otherId
          in: query
          schema:
            type: string
          description: ''
          required: true
```
Because it looks like you are telling swagger to use an object as a query parameter but shouldn't each fields be declared individually inside the swagger instead?
